[2024-07-24T00:01:10.018+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T00:01:10.038+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_script_dag.run_elt_script scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T00:01:10.043+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_script_dag.run_elt_script scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T00:01:10.043+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-24T00:01:10.051+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_elt_script> on 2024-07-23 00:00:00+00:00
[2024-07-24T00:01:10.057+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=776) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T00:01:10.058+0000] {standard_task_runner.py:64} INFO - Started process 778 to run task
[2024-07-24T00:01:10.058+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_script_dag', 'run_elt_script', 'scheduled__2024-07-23T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpy2v7ovrm']
[2024-07-24T00:01:10.060+0000] {standard_task_runner.py:91} INFO - Job 79: Subtask run_elt_script
[2024-07-24T00:01:10.096+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_script_dag.run_elt_script scheduled__2024-07-23T00:00:00+00:00 [running]> on host fd5ebbb8d998
[2024-07-24T00:01:10.151+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_script_dag' AIRFLOW_CTX_TASK_ID='run_elt_script' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-23T00:00:00+00:00'
[2024-07-24T00:01:10.153+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T00:01:10.154+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-24T00:01:10.154+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/elt_script.py']
[2024-07-24T00:01:10.164+0000] {subprocess.py:86} INFO - Output:
[2024-07-24T00:01:20.090+0000] {subprocess.py:93} INFO - ELT script started...
[2024-07-24T00:01:20.091+0000] {subprocess.py:93} INFO - fetching videos...
[2024-07-24T00:01:20.091+0000] {subprocess.py:93} INFO - fetching videos...
[2024-07-24T00:01:20.092+0000] {subprocess.py:93} INFO - fetching videos...
[2024-07-24T00:01:20.092+0000] {subprocess.py:93} INFO - fetching videos...
[2024-07-24T00:01:20.092+0000] {subprocess.py:93} INFO - could not translate host name "postgres1" to address: Name or service not known
[2024-07-24T00:01:20.093+0000] {subprocess.py:93} INFO - 
[2024-07-24T00:01:20.093+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-07-24T00:01:20.093+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/elt_script.py", line 54, in <module>
[2024-07-24T00:01:20.094+0000] {subprocess.py:93} INFO -     cursor.execute(insert_query, (formatted_time, rank, current_video['snippet']['title'], current_video['id'], current_video['snippet']['publishedAt'], current_video['snippet']['channelId'], current_video['snippet']['description'], current_video['snippet']['thumbnails'].get('maxres', current_video['snippet']['thumbnails'].get('default', {'url': ''}))['url'], current_video['contentDetails']['dimension'], current_video['statistics']['viewCount'], current_video['statistics']['likeCount'], current_video['statistics'].get('commentCount', -1), current_video['statistics']['favoriteCount'], current_video['snippet']['categoryId']))
[2024-07-24T00:01:20.094+0000] {subprocess.py:93} INFO -     ^^^^^^
[2024-07-24T00:01:20.094+0000] {subprocess.py:93} INFO - NameError: name 'cursor' is not defined
[2024-07-24T00:01:20.130+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-24T00:01:20.132+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T00:01:20.139+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-24T00:01:20.143+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=elt_script_dag, task_id=run_elt_script, run_id=scheduled__2024-07-23T00:00:00+00:00, execution_date=20240723T000000, start_date=20240724T000110, end_date=20240724T000120
[2024-07-24T00:01:20.156+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 79 for task run_elt_script (Bash command failed. The command returned a non-zero exit code 1.; 778)
[2024-07-24T00:01:20.172+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T00:01:20.185+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T00:01:20.187+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
