[2024-07-25T19:42:09.978+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T19:42:09.994+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_script_dag.run_elt_script scheduled__2024-07-24T00:00:00+00:00 [queued]>
[2024-07-25T19:42:10.001+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_script_dag.run_elt_script scheduled__2024-07-24T00:00:00+00:00 [queued]>
[2024-07-25T19:42:10.002+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-25T19:42:10.012+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_elt_script> on 2024-07-24 00:00:00+00:00
[2024-07-25T19:42:10.017+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=77) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-25T19:42:10.018+0000] {standard_task_runner.py:64} INFO - Started process 79 to run task
[2024-07-25T19:42:10.019+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_script_dag', 'run_elt_script', 'scheduled__2024-07-24T00:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpu5zka2us']
[2024-07-25T19:42:10.020+0000] {standard_task_runner.py:91} INFO - Job 107: Subtask run_elt_script
[2024-07-25T19:42:10.053+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_script_dag.run_elt_script scheduled__2024-07-24T00:00:00+00:00 [running]> on host 95376c4fb2d6
[2024-07-25T19:42:10.112+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_script_dag' AIRFLOW_CTX_TASK_ID='run_elt_script' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T00:00:00+00:00'
[2024-07-25T19:42:10.113+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T19:42:10.114+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-25T19:42:10.114+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/elt_script.py']
[2024-07-25T19:42:10.124+0000] {subprocess.py:86} INFO - Output:
[2024-07-25T19:42:10.456+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-07-25T19:42:10.456+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/elt_script.py", line 2, in <module>
[2024-07-25T19:42:10.458+0000] {subprocess.py:93} INFO -     from crawlers import results_crawler, channels_crawler
[2024-07-25T19:42:10.458+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/crawlers.py", line 2, in <module>
[2024-07-25T19:42:10.459+0000] {subprocess.py:93} INFO -     import sql_operations
[2024-07-25T19:42:10.459+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'sql_operations'
[2024-07-25T19:42:10.474+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-25T19:42:10.475+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T19:42:10.484+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-25T19:42:10.487+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=elt_script_dag, task_id=run_elt_script, run_id=scheduled__2024-07-24T00:00:00+00:00, execution_date=20240724T000000, start_date=20240725T194209, end_date=20240725T194210
[2024-07-25T19:42:10.498+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 107 for task run_elt_script (Bash command failed. The command returned a non-zero exit code 1.; 79)
[2024-07-25T19:42:10.513+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T19:42:10.530+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T19:42:10.533+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
