[2024-07-23T04:51:25.132+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-23T04:51:25.149+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_script_dag.run_elt_script manual__2024-07-23T04:50:21.070398+00:00 [queued]>
[2024-07-23T04:51:25.155+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_script_dag.run_elt_script manual__2024-07-23T04:50:21.070398+00:00 [queued]>
[2024-07-23T04:51:25.156+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-23T04:51:25.167+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_elt_script> on 2024-07-23 04:50:21.070398+00:00
[2024-07-23T04:51:25.173+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=81) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-23T04:51:25.175+0000] {standard_task_runner.py:64} INFO - Started process 83 to run task
[2024-07-23T04:51:25.175+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_script_dag', 'run_elt_script', 'manual__2024-07-23T04:50:21.070398+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpml5tfx9s']
[2024-07-23T04:51:25.176+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask run_elt_script
[2024-07-23T04:51:25.210+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_script_dag.run_elt_script manual__2024-07-23T04:50:21.070398+00:00 [running]> on host e25afa2f1daa
[2024-07-23T04:51:25.271+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_script_dag' AIRFLOW_CTX_TASK_ID='run_elt_script' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T04:50:21.070398+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-23T04:50:21.070398+00:00'
[2024-07-23T04:51:25.273+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-23T04:51:25.274+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-23T04:51:25.274+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts//elt_script.py']
[2024-07-23T04:51:25.285+0000] {subprocess.py:86} INFO - Output:
[2024-07-23T04:51:25.335+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-07-23T04:51:25.335+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts//elt_script.py", line 1, in <module>
[2024-07-23T04:51:25.336+0000] {subprocess.py:93} INFO -     from crawlers import results_crawler, channels_crawler
[2024-07-23T04:51:25.336+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'crawlers'
[2024-07-23T04:51:25.339+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-23T04:51:25.339+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-23T04:51:25.347+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-23T04:51:25.350+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=elt_script_dag, task_id=run_elt_script, run_id=manual__2024-07-23T04:50:21.070398+00:00, execution_date=20240723T045021, start_date=20240723T045125, end_date=20240723T045125
[2024-07-23T04:51:25.359+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 39 for task run_elt_script (Bash command failed. The command returned a non-zero exit code 1.; 83)
[2024-07-23T04:51:25.389+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-23T04:51:25.401+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-23T04:51:25.402+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
